version: '3'
#https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose-ru
services:

  #PHP Service
  app:
    build:
      context: dockerfile/app
      dockerfile: Dockerfile
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/project
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    tty: true
    ports:
      - ${WEBSERVICE_HTTP_PORT}:80
    volumes:
      - ./:/project
      - ./dockerfile/webserver/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
         - subnet: 172.124.122.0/24
